import { Box, Stack, Typography } from "@mui/material";
import PeopleAltRounded from "@mui/icons-material/PeopleAltRounded";
import PaymentsRounded from "@mui/icons-material/PaymentsRounded";
import EventAvailableRounded from "@mui/icons-material/EventAvailableRounded";
import CorePage from "@/components/commercial/CorePage";
import { portalLinks } from "@/config/portalLinks";

function Preview() { return <Box sx={{ bgcolor: "#102A27", borderRadius: 4, p: { xs: 2, md: 3 }, transform: { md: "rotate(1.5deg)" }, boxShadow: "0 35px 90px rgba(16,42,39,.2)" }}><Typography variant="overline" sx={{ color: "#6DD5C4" }}>Live church pulse</Typography><Box sx={{ bgcolor: "white", borderRadius: 2.5, mt: 2, p: 3 }}><Typography variant="h3">Sunday, clearly.</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>Everything your team needs before the next service.</Typography><Stack spacing={1.2} sx={{ mt: 4 }}>{[[PeopleAltRounded,"1,284","members"],[PaymentsRounded,"GHS 42,680","giving this month"],[EventAvailableRounded,"7","events ahead"]].map(([Icon,value,label]) => { const I=Icon as typeof PeopleAltRounded; return <Box key={String(label)} sx={{ display:"grid",gridTemplateColumns:"42px 1fr auto",gap:2,alignItems:"center",p:1.6,bgcolor:"#F3FAF7",borderRadius:2 }}><Box sx={{width:40,height:40,borderRadius:1.5,bgcolor:"#DFF6F0",display:"grid",placeItems:"center"}}><I sx={{fontSize:20}}/></Box><Typography sx={{ fontWeight: 600 }}>{label as string}</Typography><Typography sx={{ fontWeight: 700 }}>{value as string}</Typography></Box>; })}</Stack></Box></Box>; }

export default function FeaturesPage() { return <CorePage eyebrow="The complete platform" title={<>Every part of church life, <Box component="span" color="primary.main">working together.</Box></>} intro="Altar OS connects people, giving, attendance, communication, care and insight in one operating system—without flattening ministry into admin work." primary={{label:"Create your church",href:portalLinks.churchRegister}} secondary={{label:"See pricing",to:"/pricing"}} preview={<Preview />} statement="Less system work. More ministry context." statementCopy="Each module shares the same church, member and branch context, so updates travel with the work instead of dying in another spreadsheet." features={[{number:"01",title:"People and belonging",copy:"Member, household, department, group and discipleship records that reflect how people actually belong.",note:"Role-based access for sensitive pastoral context"},{number:"02",title:"Giving and stewardship",copy:"MoMo, card and physical cash records with pledges, campaigns, statements and finance controls.",note:"Funds settle directly to the church"},{number:"03",title:"Gatherings and teams",copy:"Events, RSVP, offline QR attendance, volunteer rotas and reminders for every recurring service."},{number:"04",title:"Communication and care",copy:"Targeted WhatsApp, SMS, email and push alongside pastoral follow-up, welfare and prayer workflows."}]} proofs={[{value:"16",label:"product domains in scope"},{value:"8+",label:"local languages planned"},{value:"24/7",label:"member web access"},{value:"1",label:"shared church record"}]} seoTitle="Altar OS platform" seoDescription="Explore the connected church management platform for members, giving, attendance, communication, pastoral care and multi-branch ministry." />; }
