import { Link as RouterLink } from "react-router-dom";
import { Box, Button, Container, Stack, Typography } from "@mui/material";
import ArrowForwardRounded from "@mui/icons-material/ArrowForwardRounded";
import ChurchRounded from "@mui/icons-material/ChurchRounded";
import PersonRounded from "@mui/icons-material/PersonRounded";
import LoginRounded from "@mui/icons-material/LoginRounded";
import SEO from "@/components/ui/SEO";
import { portalLinks } from "@/config/portalLinks";

const paths=[
  {Icon:ChurchRounded,label:"I lead or administer a church",title:"Create your church workspace",copy:"Start the free plan, set up your church profile, then invite pastors, administrators and finance team members.",actions:[{label:"Create church account",href:portalLinks.churchRegister,primary:true},{label:"Church staff login",href:portalLinks.churchLogin}]},
  {Icon:PersonRounded,label:"I am a church member",title:"Enter the member experience",copy:"Use Altar OS from your browser when you do not want to install the app. Access giving, events, sermons, community and your profile.",actions:[{label:"Open member web",href:portalLinks.memberLogin,primary:true},{label:"Create member account",href:portalLinks.memberRegister}]},
];

export default function GetStartedPage(){return <><SEO title="Get started" description="Create an Altar OS church workspace or access the member web application from any browser."/><Box component="section" sx={{py:{xs:9,md:15},background:"radial-gradient(circle at 50% 15%,rgba(109,213,196,.25),transparent 36%)"}}><Container maxWidth={false} sx={{maxWidth:1200}}><Box sx={{textAlign:"center",maxWidth:850,mx:"auto"}}><Typography variant="overline" color="primary.main">Choose your way in</Typography><Typography variant="h1" sx={{mt:2.5,fontSize:"clamp(3.4rem,7vw,6.8rem)"}}>One platform. Two front doors.</Typography><Typography variant="subtitle1" color="text.secondary" sx={{mt:3,maxWidth:650,mx:"auto"}}>Church teams manage ministry in the dashboard. Members participate through the mobile app or the full browser experience.</Typography></Box><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"1fr 1fr"},gap:2,mt:{xs:7,md:10}}}>{paths.map(({Icon,label,title,copy,actions},i)=><Box key={label} sx={{p:{xs:3,md:5},borderRadius:3,bgcolor:i===0?"#102A27":"#DFF6F0",color:i===0?"white":"#102A27",minHeight:440,display:"flex",flexDirection:"column"}}><Box sx={{width:54,height:54,borderRadius:2,bgcolor:i===0?"rgba(109,213,196,.16)":"rgba(16,42,39,.08)",display:"grid",placeItems:"center"}}><Icon sx={{color:i===0?"#6DD5C4":"#157F73"}}/></Box><Typography variant="overline" sx={{mt:5,color:i===0?"#6DD5C4":"#157F73"}}>{label}</Typography><Typography variant="h3" sx={{mt:1.5,color:"inherit",maxWidth:420}}>{title}</Typography><Typography sx={{mt:2,color:i===0?"rgba(255,255,255,.65)":"text.secondary",maxWidth:470}}>{copy}</Typography><Stack direction={{xs:"column",sm:"row"}} spacing={1.5} sx={{mt:"auto",pt:5,alignItems:{sm:"center"}}}>{actions.map(action=><Button key={action.label} href={action.href} variant={action.primary?"contained":"text"} endIcon={action.primary?<ArrowForwardRounded/>:<LoginRounded/>} sx={!action.primary&&i===0?{color:"white"}:{}}>{action.label}</Button>)}</Stack></Box>)}</Box><Typography variant="body2" color="text.secondary" sx={{textAlign:"center",mt:5}}>Need help choosing? <Box component={RouterLink} to="/contact" sx={{color:"primary.main",fontWeight:650}}>Talk to our team</Box></Typography></Container></Box></>}
