package privacy

import (
	"context"
	"fmt"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// Retention limits (Ghana Data Protection Act 2012, s.24).
//
// Act 843 s.24 says personal data "shall not be kept for longer than is
// necessary" for the purpose it was collected for. There is no number in the
// statute, because the necessary period depends on the purpose — so the
// obligation is to have DECIDED a period per purpose and to actually enforce
// it, not to pick a figure that sounds prudent.
//
// # What is deliberately NOT here
//
// Nothing a church needs to run, and nothing anyone is required to keep:
//
//   - Giving, pledges and the ledger. Six years under the Revenue
//     Administration Act 2016 s.28, and the church's own accounts must
//     reconcile. These are handled by the deletion path instead, which
//     anonymises rather than removes.
//   - Members, attendance, events, the rota, sermons. A congregation's own
//     records, kept for as long as the church wants them. Deleting a member's
//     attendance because it turned three years old would be destroying the
//     church's history, not protecting anybody's privacy.
//   - Deletion receipts. They are the evidence a request was honoured, and
//     they hold no identity once purged.
//
// What IS here is operational exhaust: data generated BY the system rather
// than entered by the church, which serves a purpose that expires.
//
// # Why this is a sweeper and not a TTL index
//
// A Mongo TTL index would be simpler and is the obvious answer. It is rejected
// because it deletes silently and unconditionally: no log, no count, no way to
// answer "what did we remove last month" during an audit, and no chance to
// exclude a row that turns out to matter. For a compliance control, being able
// to show what it did is most of the value.

// RetentionRule is one category with a decided lifetime.
type RetentionRule struct {
	Collection string `json:"collection"`
	Label      string `json:"label"`
	// Field is the timestamp aged from.
	Field   string        `json:"field"`
	KeepFor time.Duration `json:"-"`
	// KeepForDays is the readable form, for the policy page.
	KeepForDays int `json:"keepForDays"`
	// Because states the purpose the period is derived FROM, which is what
	// s.24 actually asks a controller to be able to explain.
	Because string `json:"because"`
	// Only narrows the rule further — a status that means "finished".
	Only bson.M `json:"-"`
}

// RetentionPolicy is every decided period.
var RetentionPolicy = []RetentionRule{
	{
		Collection: "notifications", Label: "Message delivery history",
		Field: "createdAt", KeepFor: 24 * 30 * 24 * time.Hour, KeepForDays: 720,
		Because: "A church may need to show that a giving receipt or a service " +
			"notice was sent, and two years covers any reasonable dispute. The " +
			"message body is not needed after that.",
	},
	{
		Collection: "notification_devices", Label: "Registered devices",
		Field: "updatedAt", KeepFor: 12 * 30 * 24 * time.Hour, KeepForDays: 360,
		Because: "A push token not seen for a year belongs to a phone that is " +
			"gone. Keeping it serves nobody and it is an identifier for a " +
			"specific device.",
	},
	{
		Collection: "payment_methods", Label: "Unused saved payment methods",
		Field: "lastUsedAt", KeepFor: 24 * 30 * 24 * time.Hour, KeepForDays: 720,
		Because: "A card or wallet nobody has given with for two years is a " +
			"credential we are holding for no reason. Removing it costs the " +
			"member one extra step next time and removes a live payment " +
			"authorisation from the database.",
	},
	{
		Collection: "audit_log", Label: "Access and administration log",
		Field: "at", KeepFor: 7 * 365 * 24 * time.Hour, KeepForDays: 2555,
		Because: "Seven years, matching the longest record-keeping obligation a " +
			"church has. This is the log that answers 'did somebody look at a " +
			"welfare case', so it outlives almost everything else on purpose.",
	},
	{
		Collection: "social_reports", Label: "Resolved moderation reports",
		Field: "resolvedAt", KeepFor: 24 * 30 * 24 * time.Hour, KeepForDays: 720,
		Because: "A moderator's decision is worth keeping while it might be " +
			"questioned. Two years after it was settled, it identifies who " +
			"reported whom and serves no other purpose.",
		Only: bson.M{"status": bson.M{"$ne": "open"}},
	},
	{
		Collection: "discipleship_tasks", Label: "Completed follow-up",
		Field: "closedAt", KeepFor: 24 * 30 * 24 * time.Hour, KeepForDays: 720,
		Because: "Closed follow-up records what was said about somebody's first " +
			"visit. The pastoral value is in the weeks after; two years later " +
			"it is a note about a person that nobody is using.",
		Only: bson.M{"closedAt": bson.M{"$exists": true}},
	},
}

// RetentionResult reports one enforcement pass.
type RetentionResult struct {
	// Removed counts per label, so a run can be reported rather than merely
	// having happened — see the note on why this is not a TTL index.
	Removed map[string]int64 `json:"removed"`
	Total   int64            `json:"total"`
}

// EnforceRetention removes data past its decided lifetime.
//
// Bounded per collection so a first run against years of backlog works through
// it over several passes rather than one that times out and deletes nothing.
func (s *Service) EnforceRetention(ctx context.Context) (*RetentionResult, error) {
	now := s.now()
	out := &RetentionResult{Removed: map[string]int64{}}

	for _, rule := range RetentionPolicy {
		cutoff := now.Add(-rule.KeepFor)

		filter := bson.M{rule.Field: bson.M{"$lt": cutoff}}
		for k, v := range rule.Only {
			filter[k] = v
		}

		res, err := s.db.Tenant(rule.Collection).DeleteMany(ctx, filter)
		if err != nil {
			// One category's failure must not stop the others: a malformed
			// document in the audit log should not mean stale push tokens are
			// kept for another year.
			continue
		}
		if res.DeletedCount > 0 {
			out.Removed[rule.Label] = res.DeletedCount
			out.Total += res.DeletedCount
		}
	}
	return out, nil
}

// RetentionDisclosure is the policy in the form a person can read.
//
// Act 843 s.32 gives a data subject the right to know how long their data is
// kept, not merely what is held — so this is part of the answer to a subject
// access request, and it is generated from the same rules the sweeper obeys.
func RetentionDisclosure() []RetentionRule {
	out := make([]RetentionRule, len(RetentionPolicy))
	copy(out, RetentionPolicy)
	return out
}

// String describes a rule for a log line.
func (r RetentionRule) String() string {
	return fmt.Sprintf("%s after %d days", r.Label, r.KeepForDays)
}
