import { Box, Button, Container, Stack, Typography } from "@mui/material";
import CheckRounded from "@mui/icons-material/CheckRounded";
import ArrowForwardRounded from "@mui/icons-material/ArrowForwardRounded";
import { portalLinks } from "@/config/portalLinks";

const tiers = [
  { name:"Starter", price:"GHS 0", cadence:"forever", description:"For a local assembly building its first shared digital home.", members:"Up to 100 members", features:["Member and household records","Giving and events","Member web and mobile access","Community support"], cta:"Create your church", href:portalLinks.churchRegister },
  { name:"Growth", price:"GHS 249", cadence:"per month", description:"For growing churches coordinating weekly ministry across teams.", members:"Up to 500 members", features:["Everything in Starter","WhatsApp and SMS broadcasts","Pledges and giving statements","Attendance analytics","Email support"], cta:"Start with Growth", href:portalLinks.churchRegister },
  { name:"Ministry", price:"GHS 749", cadence:"per month", description:"For established churches with branches, departments and controls.", members:"Unlimited members", features:["Everything in Growth","Multi-branch reporting","Volunteer rotas","Responsible AI tools","Finance controls and audit trail","Priority support"], cta:"Choose Ministry", href:portalLinks.churchRegister, featured:true },
  { name:"Denomination", price:"Custom", cadence:"annual agreement", description:"For multi-campus networks, districts and national structures.", members:"Unlimited branches", features:["Consolidated HQ analytics","Data residency options","Dedicated onboarding","Service-level agreement","Named account partner"], cta:"Talk to us", href:"/contact", internal:true },
];

export default function PricingSection(){return <Box component="section" id="pricing" sx={{py:{xs:9,md:15},bgcolor:"#F7FBF8"}}><Container maxWidth={false} sx={{maxWidth:1360}}><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:".75fr 1.25fr"},gap:{xs:4,md:10},mb:{xs:7,md:10}}}><Box><Typography variant="overline" color="primary.main">Simple, GHS pricing</Typography><Typography variant="h2" sx={{mt:2}}>Start free. Pay when the platform earns its place.</Typography></Box><Typography color="text.secondary" sx={{maxWidth:560,alignSelf:"end"}}>No setup fee and no card required for Starter. Giving settles directly to your church’s own payment subaccount; standard processing and disclosed platform fees apply.</Typography></Box><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"1fr 1fr"},gap:2}}>{tiers.map(tier=><Box key={tier.name} sx={{p:{xs:3,md:4.5},borderRadius:3,bgcolor:tier.featured?"#102A27":"#FFFFFF",color:tier.featured?"white":"text.primary",border:"1px solid",borderColor:tier.featured?"#102A27":"divider",minHeight:500,display:"flex",flexDirection:"column"}}><Stack direction="row" sx={{justifyContent:"space-between",alignItems:"start"}}><Box><Typography variant="overline" sx={{color:tier.featured?"#6DD5C4":"primary.main"}}>{tier.name}</Typography><Typography variant="h3" sx={{mt:2,color:"inherit"}}>{tier.price}</Typography><Typography variant="body2" sx={{color:tier.featured?"rgba(255,255,255,.55)":"text.secondary"}}>{tier.cadence}</Typography></Box><Typography variant="caption" sx={{px:1.5,py:.7,borderRadius:10,bgcolor:tier.featured?"#6DD5C4":"#DFF6F0",color:"#102A27",fontWeight:700}}>{tier.members}</Typography></Stack><Typography sx={{mt:3,maxWidth:430,color:tier.featured?"rgba(255,255,255,.68)":"text.secondary"}}>{tier.description}</Typography><Stack spacing={1.3} sx={{mt:4,mb:4}}>{tier.features.map(feature=><Stack key={feature} direction="row" spacing={1.2} sx={{alignItems:"start"}}><CheckRounded sx={{fontSize:18,color:tier.featured?"#6DD5C4":"primary.main",mt:.25}}/><Typography variant="body2" sx={{color:tier.featured?"rgba(255,255,255,.8)":"text.primary"}}>{feature}</Typography></Stack>)}</Stack><Button href={tier.href} variant={tier.featured?"contained":"outlined"} endIcon={<ArrowForwardRounded/>} sx={{mt:"auto",alignSelf:"start",...(tier.featured&&{bgcolor:"#6DD5C4",color:"#102A27","&:hover":{bgcolor:"#8BE1D3"}})}}>{tier.cta}</Button></Box>)}</Box><Typography variant="caption" color="text.secondary" sx={{display:"block",mt:4}}>Prices shown are current launch pricing and may change before general availability. Any transaction charge is shown before payment and separated from church-recognised income.</Typography></Container></Box>}
