import { Link as RouterLink } from "react-router-dom";
import { Box, Button, Container, Divider, Link, Stack, Typography } from "@mui/material";
import ArrowOutwardRounded from "@mui/icons-material/ArrowOutwardRounded";
import { Brand } from "./Navbar";
import { portalLinks } from "@/config/portalLinks";

const product=[["Platform","/features"],["Pricing","/pricing"],["Churches","/solutions/churches"],["Member web","/mobile-app"],["Responsible AI","/ai-tools"]];
const company=[["About","/about"],["Contact","/contact"],["Journal","/blog"],["Help","/help"],["Privacy","/privacy"],["Terms","/terms"]];

export default function Footer(){return <Box component="footer" sx={{bgcolor:"#102A27",color:"white",pt:{xs:8,md:12},pb:4}}><Container maxWidth={false} sx={{maxWidth:1360}}><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"1.1fr .9fr"},gap:7,alignItems:"end"}}><Box><Typography variant="overline" sx={{color:"#6DD5C4"}}>Your next Sunday can be clearer</Typography><Typography variant="h2" sx={{color:"white",maxWidth:720,mt:2}}>Give your whole church one dependable home.</Typography></Box><Stack direction={{xs:"column",sm:"row"}} spacing={1.5} sx={{alignItems:{sm:"center"},flexWrap:"wrap"}}><Button component={RouterLink} to="/get-started" variant="contained" endIcon={<ArrowOutwardRounded/>}>Start free</Button><Button href={portalLinks.churchLogin} sx={{color:"white"}}>Church staff login</Button><Button href={portalLinks.memberLogin} sx={{color:"white"}}>Member login</Button></Stack></Box><Divider sx={{my:{xs:7,md:9},borderColor:"rgba(255,255,255,.13)"}}/><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"1fr auto auto"},gap:{xs:5,md:9}}}><Box sx={{"& a":{color:"white"}}}><Brand/><Typography variant="body2" sx={{color:"rgba(255,255,255,.48)",mt:2,maxWidth:300}}>Built in Accra for churches and members across Africa.</Typography></Box>{[{label:"Product",items:product},{label:"Company",items:company}].map(group=><Box key={group.label}><Typography variant="overline" sx={{color:"#6DD5C4"}}>{group.label}</Typography><Stack spacing={1.2} sx={{mt:2}}>{group.items.map(([label,to])=><Link key={to} component={RouterLink} to={to} underline="none" sx={{color:"rgba(255,255,255,.65)",fontSize:".88rem","&:hover":{color:"#6DD5C4"}}}>{label}</Link>)}</Stack></Box>)}</Box><Divider sx={{my:4,borderColor:"rgba(255,255,255,.1)"}}/><Typography variant="caption" sx={{color:"rgba(255,255,255,.38)"}}>© {new Date().getFullYear()} Altar OS · Accra, Ghana</Typography></Container></Box>}
