// Code generated by tools/gen-go-contracts. DO NOT EDIT.
//
// Source: packages/shared-types/src/ai.ts
//
// Wire (DTO) types shared with the TypeScript frontends. Regenerate with
// `make contracts` after changing shared-types; CI fails on drift.

package contracts

type SermonOutline struct {
	ID           string `json:"id"`
	Topic        string `json:"topic"`
	Title        string `json:"title"`
	Scripture    string `json:"scripture"`
	Introduction string `json:"introduction"`
	Points       []struct {
		Title     string `json:"title"`
		Content   string `json:"content"`
		Scripture string `json:"scripture"`
	} `json:"points"`
	Conclusion        string   `json:"conclusion"`
	ApplicationPoints []string `json:"applicationPoints"`
	CreatedAt         string   `json:"createdAt"`
}

type SermonGenerateRequest struct {
	Topic          string  `json:"topic"`
	Style          *string `json:"style,omitempty"`
	Duration       *string `json:"duration,omitempty"`
	TargetAudience *string `json:"targetAudience,omitempty"`
}

type MemberInsight struct {
	ID              string         `json:"id"`
	MemberID        string         `json:"memberId"`
	MemberName      string         `json:"memberName"`
	Type            string         `json:"type"`
	Severity        string         `json:"severity"`
	Message         string         `json:"message"`
	SuggestedAction string         `json:"suggestedAction"`
	Data            map[string]any `json:"data"`
	CreatedAt       string         `json:"createdAt"`
	IsRead          bool           `json:"isRead"`
}

type PrayerChatMessage struct {
	ID         string `json:"id"`
	Role       string `json:"role"`
	Content    string `json:"content"`
	Scriptures []struct {
		Reference string `json:"reference"`
		Text      string `json:"text"`
	} `json:"scriptures,omitempty"`
	Timestamp string `json:"timestamp"`
}

type PrayerChatRequest struct {
	Message        string  `json:"message"`
	ConversationID *string `json:"conversationId,omitempty"`
}

type PrayerChatResponse struct {
	Message        PrayerChatMessage `json:"message"`
	ConversationID string            `json:"conversationId"`
}
