// Code generated by tools/gen-go-contracts. DO NOT EDIT.
//
// Source: packages/shared-types/src/api.ts
//
// Wire (DTO) types shared with the TypeScript frontends. Regenerate with
// `make contracts` after changing shared-types; CI fails on drift.

package contracts

type ApiResponse struct {
	Success bool     `json:"success"`
	Data    any      `json:"data,omitempty"`
	Message *string  `json:"message,omitempty"`
	Errors  []string `json:"errors,omitempty"`
}

type PaginatedResponse struct {
	Pagination struct {
		Page       float64 `json:"page"`
		Limit      float64 `json:"limit"`
		Total      float64 `json:"total"`
		TotalPages float64 `json:"totalPages"`
	} `json:"pagination"`
}

type PaginationQuery struct {
	Page      *float64 `json:"page,omitempty"`
	Limit     *float64 `json:"limit,omitempty"`
	SortBy    *string  `json:"sortBy,omitempty"`
	SortOrder *string  `json:"sortOrder,omitempty"`
}
