// Code generated by tools/gen-go-contracts. DO NOT EDIT.
//
// Source: packages/shared-types/src/auth.ts
//
// Wire (DTO) types shared with the TypeScript frontends. Regenerate with
// `make contracts` after changing shared-types; CI fails on drift.

package contracts

import "time"

type UserRole string

const (
	UserRoleSuperAdmin       UserRole = "SUPER_ADMIN"
	UserRoleChurchAdmin      UserRole = "CHURCH_ADMIN"
	UserRoleDepartmentLeader UserRole = "DEPARTMENT_LEADER"
	UserRoleMember           UserRole = "MEMBER"
)

type LoginMethod string

const (
	LoginMethodPhone  LoginMethod = "PHONE"
	LoginMethodEmail  LoginMethod = "EMAIL"
	LoginMethodSocial LoginMethod = "SOCIAL"
)

type User struct {
	ID string `json:"id"`
	// Linked congregation-roster identity used by member-owned domains.
	MemberID  *string   `json:"memberId,omitempty"`
	ChurchID  string    `json:"churchId"`
	Email     string    `json:"email"`
	Phone     string    `json:"phone"`
	Name      string    `json:"name"`
	Role      UserRole  `json:"role"`
	AvatarURL *string   `json:"avatarUrl,omitempty"`
	IsActive  bool      `json:"isActive"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type AuthTokens struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type LoginRequest struct {
	Email    *string     `json:"email,omitempty"`
	Phone    *string     `json:"phone,omitempty"`
	Password *string     `json:"password,omitempty"`
	Method   LoginMethod `json:"method"`
}

type RegisterRequest struct {
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Name     string `json:"name"`
	Password string `json:"password"`
	// Join an existing church. Provide this OR `churchName`, not neither.
	ChurchID *string `json:"churchId,omitempty"`
	// Register a new church and become its first CHURCH_ADMIN. Used by the
	// self-signup flow, where the registrant knows their church's name but
	// has no id yet.
	ChurchName *string `json:"churchName,omitempty"`
	// Optional founding profile captured during church onboarding.
	ChurchCity              *string  `json:"churchCity,omitempty"`
	ChurchDenomination      *string  `json:"churchDenomination,omitempty"`
	AverageWeeklyAttendance *float64 `json:"averageWeeklyAttendance,omitempty"`
	MinistryPriorities      []string `json:"ministryPriorities,omitempty"`
	// Package intent. Paid access is activated separately after billing.
	RequestedPlan *string `json:"requestedPlan,omitempty"`
}

type OtpVerifyRequest struct {
	Phone *string `json:"phone,omitempty"`
	Email *string `json:"email,omitempty"`
	OTP   string  `json:"otp"`
}
