// Code generated by tools/gen-go-contracts. DO NOT EDIT.
//
// Source: packages/shared-types/src/church.ts
//
// Wire (DTO) types shared with the TypeScript frontends. Regenerate with
// `make contracts` after changing shared-types; CI fails on drift.

package contracts

import "time"

type ChurchPlan string

const (
	ChurchPlanFree       ChurchPlan = "free"
	ChurchPlanBasic      ChurchPlan = "basic"
	ChurchPlanPro        ChurchPlan = "pro"
	ChurchPlanEnterprise ChurchPlan = "enterprise"
)

type Church struct {
	ID                      string      `json:"id"`
	Name                    string      `json:"name"`
	Slug                    string      `json:"slug"`
	Address                 string      `json:"address"`
	City                    string      `json:"city"`
	Country                 string      `json:"country"`
	Phone                   string      `json:"phone"`
	Email                   string      `json:"email"`
	Website                 *string     `json:"website,omitempty"`
	LogoURL                 *string     `json:"logoUrl,omitempty"`
	BannerURL               *string     `json:"bannerUrl,omitempty"`
	Timezone                string      `json:"timezone"`
	Currency                string      `json:"currency"`
	Plan                    ChurchPlan  `json:"plan"`
	RequestedPlan           *ChurchPlan `json:"requestedPlan,omitempty"`
	Denomination            *string     `json:"denomination,omitempty"`
	AverageWeeklyAttendance *float64    `json:"averageWeeklyAttendance,omitempty"`
	MinistryPriorities      []string    `json:"ministryPriorities,omitempty"`
	IsActive                bool        `json:"isActive"`
	CreatedAt               time.Time   `json:"createdAt"`
	UpdatedAt               time.Time   `json:"updatedAt"`
}

type ChurchSettings struct {
	ID                      string  `json:"id"`
	ChurchID                string  `json:"churchId"`
	AllowPublicRegistration bool    `json:"allowPublicRegistration"`
	DefaultLanguage         string  `json:"defaultLanguage"`
	FiscalYearStart         float64 `json:"fiscalYearStart"`
}
