// Code generated by tools/gen-go-contracts. DO NOT EDIT.
//
// Source: packages/shared-types/src/communication.ts
//
// Wire (DTO) types shared with the TypeScript frontends. Regenerate with
// `make contracts` after changing shared-types; CI fails on drift.

package contracts

import "time"

type MessageChannel string

const (
	MessageChannelPush  MessageChannel = "PUSH"
	MessageChannelSMS   MessageChannel = "SMS"
	MessageChannelEmail MessageChannel = "EMAIL"
)

type ActivityLevel string

const (
	ActivityLevelActive   ActivityLevel = "active"
	ActivityLevelInactive ActivityLevel = "inactive"
	ActivityLevelAll      ActivityLevel = "all"
)

type MessageTargetFilter struct {
	DepartmentIds  []string       `json:"departmentIds,omitempty"`
	Locations      []string       `json:"locations,omitempty"`
	MemberStatuses []MemberStatus `json:"memberStatuses,omitempty"`
	ActivityLevel  *ActivityLevel `json:"activityLevel,omitempty"`
}

type Message struct {
	ID           string               `json:"id"`
	ChurchID     string               `json:"churchId"`
	SenderID     string               `json:"senderId"`
	Title        string               `json:"title"`
	Body         string               `json:"body"`
	Channel      MessageChannel       `json:"channel"`
	TargetFilter *MessageTargetFilter `json:"targetFilter,omitempty"`
	SentAt       *time.Time           `json:"sentAt,omitempty"`
	CreatedAt    time.Time            `json:"createdAt"`
}

type Announcement struct {
	ID        string     `json:"id"`
	ChurchID  string     `json:"churchId"`
	Title     string     `json:"title"`
	Body      string     `json:"body"`
	ImageURL  *string    `json:"imageUrl,omitempty"`
	IsPinned  bool       `json:"isPinned"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	CreatedAt time.Time  `json:"createdAt"`
}

type GroupChat struct {
	ID            string   `json:"id"`
	ChurchID      string   `json:"churchId"`
	Name          string   `json:"name"`
	Description   *string  `json:"description,omitempty"`
	MemberIds     []string `json:"memberIds"`
	CreatedBy     string   `json:"createdBy"`
	ImageURL      *string  `json:"imageUrl,omitempty"`
	LastMessageAt *string  `json:"lastMessageAt,omitempty"`
	CreatedAt     string   `json:"createdAt"`
}

type ChatMessage struct {
	ID         string `json:"id"`
	GroupID    string `json:"groupId"`
	SenderID   string `json:"senderId"`
	SenderName string `json:"senderName"`
	Content    string `json:"content"`
	CreatedAt  string `json:"createdAt"`
}
