// Code generated by tools/gen-go-contracts. DO NOT EDIT.
//
// Source: packages/shared-types/src/event.ts
//
// Wire (DTO) types shared with the TypeScript frontends. Regenerate with
// `make contracts` after changing shared-types; CI fails on drift.

package contracts

import "time"

type Event struct {
	ID             string    `json:"id"`
	ChurchID       string    `json:"churchId"`
	Title          string    `json:"title"`
	Description    *string   `json:"description,omitempty"`
	Location       *string   `json:"location,omitempty"`
	StartDate      time.Time `json:"startDate"`
	EndDate        time.Time `json:"endDate"`
	IsRecurring    bool      `json:"isRecurring"`
	RecurrenceRule *string   `json:"recurrenceRule,omitempty"`
	Capacity       *float64  `json:"capacity,omitempty"`
	RsvpCount      float64   `json:"rsvpCount"`
	CheckInCode    *string   `json:"checkInCode,omitempty"`
	CreatedAt      time.Time `json:"createdAt"`
}

type CheckInMethod string

const (
	CheckInMethodQr     CheckInMethod = "QR"
	CheckInMethodManual CheckInMethod = "MANUAL"
)

type Attendance struct {
	ID          string        `json:"id"`
	EventID     string        `json:"eventId"`
	MemberID    string        `json:"memberId"`
	ChurchID    string        `json:"churchId"`
	CheckedInAt time.Time     `json:"checkedInAt"`
	Method      CheckInMethod `json:"method"`
}

type RsvpStatus string

const (
	RsvpStatusGoing    RsvpStatus = "GOING"
	RsvpStatusMaybe    RsvpStatus = "MAYBE"
	RsvpStatusNotGoing RsvpStatus = "NOT_GOING"
)

type RSVP struct {
	ID       string     `json:"id"`
	EventID  string     `json:"eventId"`
	MemberID string     `json:"memberId"`
	Status   RsvpStatus `json:"status"`
}
