// Code generated by tools/gen-go-contracts. DO NOT EDIT.
//
// Source: packages/shared-types/src/finance.ts
//
// Wire (DTO) types shared with the TypeScript frontends. Regenerate with
// `make contracts` after changing shared-types; CI fails on drift.

package contracts

import "time"

type TransactionType string

const (
	TransactionTypeTithe    TransactionType = "TITHE"
	TransactionTypeOffering TransactionType = "OFFERING"
	TransactionTypeDonation TransactionType = "DONATION"
	TransactionTypeExpense  TransactionType = "EXPENSE"
)

type PaymentMethod string

const (
	PaymentMethodMobileMoney  PaymentMethod = "MOBILE_MONEY"
	PaymentMethodCard         PaymentMethod = "CARD"
	PaymentMethodCrypto       PaymentMethod = "CRYPTO"
	PaymentMethodBankTransfer PaymentMethod = "BANK_TRANSFER"
	PaymentMethodCash         PaymentMethod = "CASH"
)

type PaymentStatus string

const (
	PaymentStatusPending   PaymentStatus = "PENDING"
	PaymentStatusCompleted PaymentStatus = "COMPLETED"
	PaymentStatusFailed    PaymentStatus = "FAILED"
	PaymentStatusRefunded  PaymentStatus = "REFUNDED"
)

type ExpenseCategory string

const (
	ExpenseCategoryUtilities   ExpenseCategory = "UTILITIES"
	ExpenseCategorySalaries    ExpenseCategory = "SALARIES"
	ExpenseCategoryMaintenance ExpenseCategory = "MAINTENANCE"
	ExpenseCategoryMissions    ExpenseCategory = "MISSIONS"
	ExpenseCategoryEvents      ExpenseCategory = "EVENTS"
	ExpenseCategorySupplies    ExpenseCategory = "SUPPLIES"
	ExpenseCategoryOther       ExpenseCategory = "OTHER"
)

type ExpenseSummaryItem struct {
	Category string  `json:"category"`
	Total    float64 `json:"total"`
}

type Transaction struct {
	ID            string           `json:"id"`
	ChurchID      string           `json:"churchId"`
	MemberID      *string          `json:"memberId,omitempty"`
	Type          TransactionType  `json:"type"`
	Amount        float64          `json:"amount"`
	Currency      string           `json:"currency"`
	PaymentMethod PaymentMethod    `json:"paymentMethod"`
	Status        PaymentStatus    `json:"status"`
	Reference     string           `json:"reference"`
	Description   *string          `json:"description,omitempty"`
	Category      *ExpenseCategory `json:"category,omitempty"`
	CampaignID    *string          `json:"campaignId,omitempty"`
	CreatedAt     time.Time        `json:"createdAt"`
}

type Campaign struct {
	ID            string    `json:"id"`
	ChurchID      string    `json:"churchId"`
	Title         string    `json:"title"`
	Description   *string   `json:"description,omitempty"`
	TargetAmount  float64   `json:"targetAmount"`
	CurrentAmount float64   `json:"currentAmount"`
	StartDate     time.Time `json:"startDate"`
	EndDate       time.Time `json:"endDate"`
	IsActive      bool      `json:"isActive"`
}
