// Code generated by tools/gen-go-contracts. DO NOT EDIT.
//
// Source: packages/shared-types/src/giving.ts
//
// Wire (DTO) types shared with the TypeScript frontends. Regenerate with
// `make contracts` after changing shared-types; CI fails on drift.

package contracts

import "time"

type GivingType string

const (
	GivingTypeTithe    GivingType = "tithe"
	GivingTypeOffering GivingType = "offering"
	GivingTypeDonation GivingType = "donation"
	GivingTypeCampaign GivingType = "campaign"
)

type GivingPaymentMethod string

const (
	GivingPaymentMethodCard         GivingPaymentMethod = "card"
	GivingPaymentMethodBankTransfer GivingPaymentMethod = "bank_transfer"
	GivingPaymentMethodMobileMoney  GivingPaymentMethod = "mobile_money"
	GivingPaymentMethodUSSD         GivingPaymentMethod = "ussd"
)

type GivingPaymentStatus string

const (
	GivingPaymentStatusPending GivingPaymentStatus = "pending"
	GivingPaymentStatusSuccess GivingPaymentStatus = "success"
	GivingPaymentStatusFailed  GivingPaymentStatus = "failed"
)

type GivingRecord struct {
	ID            string              `json:"id"`
	MemberID      string              `json:"memberId"`
	ChurchID      string              `json:"churchId"`
	Amount        float64             `json:"amount"`
	Type          GivingType          `json:"type"`
	PaymentMethod GivingPaymentMethod `json:"paymentMethod"`
	Status        GivingPaymentStatus `json:"status"`
	Reference     string              `json:"reference"`
	Note          *string             `json:"note,omitempty"`
	CampaignID    *string             `json:"campaignId,omitempty"`
	Date          time.Time           `json:"date"`
}

type GivingSummary struct {
	TotalThisMonth     float64 `json:"totalThisMonth"`
	TotalThisYear      float64 `json:"totalThisYear"`
	TitheThisMonth     float64 `json:"titheThisMonth"`
	OfferingThisMonth  float64 `json:"offeringThisMonth"`
	DonationsThisMonth float64 `json:"donationsThisMonth"`
}

type GivingCampaign struct {
	ID           string    `json:"id"`
	ChurchID     string    `json:"churchId"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	TargetAmount float64   `json:"targetAmount"`
	RaisedAmount float64   `json:"raisedAmount"`
	StartDate    time.Time `json:"startDate"`
	EndDate      time.Time `json:"endDate"`
	ImageURL     *string   `json:"imageUrl,omitempty"`
}
