// Code generated by tools/gen-go-contracts. DO NOT EDIT.
//
// Source: packages/shared-types/src/marketplace.ts
//
// Wire (DTO) types shared with the TypeScript frontends. Regenerate with
// `make contracts` after changing shared-types; CI fails on drift.

package contracts

type ChurchListing struct {
	ID           string  `json:"id"`
	ChurchID     string  `json:"churchId"`
	ChurchName   string  `json:"churchName"`
	City         string  `json:"city"`
	Country      string  `json:"country"`
	Denomination string  `json:"denomination"`
	MemberCount  float64 `json:"memberCount"`
	LogoURL      *string `json:"logoUrl,omitempty"`
	Description  string  `json:"description"`
	Services     []struct {
		Day  string `json:"day"`
		Time string `json:"time"`
		Name string `json:"name"`
	} `json:"services"`
	IsVerified  bool    `json:"isVerified"`
	Rating      float64 `json:"rating"`
	ReviewCount float64 `json:"reviewCount"`
}

type MarketplaceItem struct {
	ID          string  `json:"id"`
	ChurchID    string  `json:"churchId"`
	ChurchName  string  `json:"churchName"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Category    string  `json:"category"`
	Price       float64 `json:"price"`
	Currency    string  `json:"currency"`
	ImageURL    *string `json:"imageUrl,omitempty"`
	IsActive    bool    `json:"isActive"`
	CreatedAt   string  `json:"createdAt"`
}

type MarketplaceReview struct {
	ID           string  `json:"id"`
	ItemID       string  `json:"itemId"`
	ReviewerID   string  `json:"reviewerId"`
	ReviewerName string  `json:"reviewerName"`
	Rating       float64 `json:"rating"`
	Comment      string  `json:"comment"`
	CreatedAt    string  `json:"createdAt"`
}

type ChurchDiscoveryFilter struct {
	City         *string  `json:"city,omitempty"`
	Country      *string  `json:"country,omitempty"`
	Denomination *string  `json:"denomination,omitempty"`
	Search       *string  `json:"search,omitempty"`
	Page         *float64 `json:"page,omitempty"`
	Limit        *float64 `json:"limit,omitempty"`
}

type CollaborationRequest struct {
	ID             string `json:"id"`
	FromChurchID   string `json:"fromChurchId"`
	FromChurchName string `json:"fromChurchName"`
	ToChurchID     string `json:"toChurchId"`
	ToChurchName   string `json:"toChurchName"`
	Type           string `json:"type"`
	Title          string `json:"title"`
	Description    string `json:"description"`
	Status         string `json:"status"`
	CreatedAt      string `json:"createdAt"`
}
