// Code generated by tools/gen-go-contracts. DO NOT EDIT.
//
// Source: packages/shared-types/src/member.ts
//
// Wire (DTO) types shared with the TypeScript frontends. Regenerate with
// `make contracts` after changing shared-types; CI fails on drift.

package contracts

import "time"

type MemberStatus string

const (
	MemberStatusActive      MemberStatus = "ACTIVE"
	MemberStatusInactive    MemberStatus = "INACTIVE"
	MemberStatusVisitor     MemberStatus = "VISITOR"
	MemberStatusTransferred MemberStatus = "TRANSFERRED"
)

type Member struct {
	ID            string       `json:"id"`
	ChurchID      string       `json:"churchId"`
	UserID        *string      `json:"userId,omitempty"`
	FirstName     string       `json:"firstName"`
	LastName      string       `json:"lastName"`
	Email         *string      `json:"email,omitempty"`
	Phone         *string      `json:"phone,omitempty"`
	DateOfBirth   *time.Time   `json:"dateOfBirth,omitempty"`
	Gender        *string      `json:"gender,omitempty"`
	Address       *string      `json:"address,omitempty"`
	FamilyID      *string      `json:"familyId,omitempty"`
	DepartmentIds []string     `json:"departmentIds"`
	Status        MemberStatus `json:"status"`
	JoinDate      time.Time    `json:"joinDate"`
	Notes         *string      `json:"notes,omitempty"`
	CreatedAt     time.Time    `json:"createdAt"`
	UpdatedAt     time.Time    `json:"updatedAt"`
}

type Family struct {
	ID        string   `json:"id"`
	ChurchID  string   `json:"churchId"`
	Name      string   `json:"name"`
	MemberIds []string `json:"memberIds"`
}
