// Code generated by tools/gen-go-contracts. DO NOT EDIT.
//
// Source: packages/shared-types/src/notification.ts
//
// Wire (DTO) types shared with the TypeScript frontends. Regenerate with
// `make contracts` after changing shared-types; CI fails on drift.

package contracts

import "time"

type NotificationChannel string

const (
	NotificationChannelPush  NotificationChannel = "PUSH"
	NotificationChannelSMS   NotificationChannel = "SMS"
	NotificationChannelEmail NotificationChannel = "EMAIL"
)

type NotificationType string

const (
	NotificationTypeEventReminder  NotificationType = "EVENT_REMINDER"
	NotificationTypeGivingReminder NotificationType = "GIVING_REMINDER"
	NotificationTypeEmergencyAlert NotificationType = "EMERGENCY_ALERT"
	NotificationTypeWelcome        NotificationType = "WELCOME"
	NotificationTypeBirthday       NotificationType = "BIRTHDAY"
	NotificationTypeFollowUp       NotificationType = "FOLLOW_UP"
	NotificationTypeAnnouncement   NotificationType = "ANNOUNCEMENT"
	NotificationTypeCustom         NotificationType = "CUSTOM"
)

type NotificationStatus string

const (
	NotificationStatusPending NotificationStatus = "PENDING"
	NotificationStatusSent    NotificationStatus = "SENT"
	NotificationStatusFailed  NotificationStatus = "FAILED"
	NotificationStatusRead    NotificationStatus = "READ"
)

type Notification struct {
	ID            string              `json:"id"`
	ChurchID      string              `json:"churchId"`
	RecipientID   string              `json:"recipientId"`
	RecipientName string              `json:"recipientName"`
	Channel       NotificationChannel `json:"channel"`
	Type          NotificationType    `json:"type"`
	Title         string              `json:"title"`
	Body          string              `json:"body"`
	Status        NotificationStatus  `json:"status"`
	ScheduledAt   *time.Time          `json:"scheduledAt,omitempty"`
	SentAt        *time.Time          `json:"sentAt,omitempty"`
	ReadAt        *time.Time          `json:"readAt,omitempty"`
	Metadata      map[string]any      `json:"metadata"`
	CreatedAt     time.Time           `json:"createdAt"`
}

type NotificationPreference struct {
	ID              string `json:"id"`
	UserID          string `json:"userId"`
	ChurchID        string `json:"churchId"`
	EmailEnabled    bool   `json:"emailEnabled"`
	SmsEnabled      bool   `json:"smsEnabled"`
	PushEnabled     bool   `json:"pushEnabled"`
	EventReminders  bool   `json:"eventReminders"`
	GivingReminders bool   `json:"givingReminders"`
	EmergencyAlerts bool   `json:"emergencyAlerts"`
	Announcements   bool   `json:"announcements"`
}

type NotificationTemplate struct {
	ID        string              `json:"id"`
	ChurchID  string              `json:"churchId"`
	Type      NotificationType    `json:"type"`
	Channel   NotificationChannel `json:"channel"`
	Subject   string              `json:"subject"`
	Body      string              `json:"body"`
	IsDefault bool                `json:"isDefault"`
}

type SendNotificationRequest struct {
	RecipientIds []string            `json:"recipientIds"`
	Channel      NotificationChannel `json:"channel"`
	Type         NotificationType    `json:"type"`
	Title        string              `json:"title"`
	Body         string              `json:"body"`
	ScheduledAt  *time.Time          `json:"scheduledAt,omitempty"`
	Metadata     map[string]any      `json:"metadata,omitempty"`
}

type BulkNotificationRequest struct {
	ChurchID     string `json:"churchId"`
	TargetFilter struct {
		DepartmentIds  []string       `json:"departmentIds,omitempty"`
		MemberStatuses []MemberStatus `json:"memberStatuses,omitempty"`
		All            *bool          `json:"all,omitempty"`
	} `json:"targetFilter"`
	Channel NotificationChannel `json:"channel"`
	Type    NotificationType    `json:"type"`
	Title   string              `json:"title"`
	Body    string              `json:"body"`
}
