// Code generated by tools/gen-go-contracts. DO NOT EDIT.
//
// Source: packages/shared-types/src/social.ts
//
// Wire (DTO) types shared with the TypeScript frontends. Regenerate with
// `make contracts` after changing shared-types; CI fails on drift.

package contracts

import "time"

type PostType string

const (
	PostTypeGeneral      PostType = "general"
	PostTypeTestimony    PostType = "testimony"
	PostTypePraiseReport PostType = "praise_report"
)

type SocialPost struct {
	ID              string    `json:"id"`
	ChurchID        string    `json:"churchId"`
	AuthorID        string    `json:"authorId"`
	AuthorName      string    `json:"authorName"`
	AuthorAvatarURL *string   `json:"authorAvatarUrl,omitempty"`
	Content         string    `json:"content"`
	Type            PostType  `json:"type"`
	ImageURL        *string   `json:"imageUrl,omitempty"`
	LikesCount      float64   `json:"likesCount"`
	CommentsCount   float64   `json:"commentsCount"`
	CreatedAt       time.Time `json:"createdAt"`
}

type SocialComment struct {
	ID              string    `json:"id"`
	PostID          string    `json:"postId"`
	AuthorID        string    `json:"authorId"`
	AuthorName      string    `json:"authorName"`
	AuthorAvatarURL *string   `json:"authorAvatarUrl,omitempty"`
	Content         string    `json:"content"`
	CreatedAt       time.Time `json:"createdAt"`
}
