// Code generated by tools/gen-go-contracts. DO NOT EDIT.
//
// Source: packages/shared-types/src/spiritual.ts
//
// Wire (DTO) types shared with the TypeScript frontends. Regenerate with
// `make contracts` after changing shared-types; CI fails on drift.

package contracts

import "time"

type Devotional struct {
	ID            string    `json:"id"`
	ChurchID      string    `json:"churchId"`
	Title         string    `json:"title"`
	Scripture     string    `json:"scripture"`
	ScriptureText string    `json:"scriptureText"`
	Content       string    `json:"content"`
	Date          time.Time `json:"date"`
	Author        string    `json:"author"`
	ImageURL      *string   `json:"imageUrl,omitempty"`
}

type Sermon struct {
	ID           string    `json:"id"`
	ChurchID     string    `json:"churchId"`
	Title        string    `json:"title"`
	Speaker      string    `json:"speaker"`
	Date         time.Time `json:"date"`
	Duration     string    `json:"duration"`
	ThumbnailURL *string   `json:"thumbnailUrl,omitempty"`
	AudioURL     *string   `json:"audioUrl,omitempty"`
	VideoURL     *string   `json:"videoUrl,omitempty"`
	Description  string    `json:"description"`
	Series       *string   `json:"series,omitempty"`
}

type PrayerRequest struct {
	ID          string    `json:"id"`
	ChurchID    string    `json:"churchId"`
	MemberID    string    `json:"memberId"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	IsAnonymous bool      `json:"isAnonymous"`
	PrayerCount float64   `json:"prayerCount"`
	AuthorName  *string   `json:"authorName,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
}
