// Code generated by tools/gen-go-contracts. DO NOT EDIT.
//
// Source: packages/shared-types/src/welfare.ts
//
// Wire (DTO) types shared with the TypeScript frontends. Regenerate with
// `make contracts` after changing shared-types; CI fails on drift.

package contracts

import "time"

type WelfareCategory string

const (
	WelfareCategoryFinancial  WelfareCategory = "financial"
	WelfareCategoryMedical    WelfareCategory = "medical"
	WelfareCategoryFood       WelfareCategory = "food"
	WelfareCategoryHousing    WelfareCategory = "housing"
	WelfareCategoryCounseling WelfareCategory = "counseling"
	WelfareCategoryOther      WelfareCategory = "other"
)

type WelfareUrgency string

const (
	WelfareUrgencyLow      WelfareUrgency = "low"
	WelfareUrgencyMedium   WelfareUrgency = "medium"
	WelfareUrgencyHigh     WelfareUrgency = "high"
	WelfareUrgencyCritical WelfareUrgency = "critical"
)

type WelfareStatus string

const (
	WelfareStatusPending     WelfareStatus = "pending"
	WelfareStatusUnderReview WelfareStatus = "under_review"
	WelfareStatusApproved    WelfareStatus = "approved"
	WelfareStatusFulfilled   WelfareStatus = "fulfilled"
	WelfareStatusDeclined    WelfareStatus = "declined"
)

type WelfareRequest struct {
	ID          string          `json:"id"`
	ChurchID    string          `json:"churchId"`
	MemberID    string          `json:"memberId"`
	Category    WelfareCategory `json:"category"`
	Description string          `json:"description"`
	Urgency     WelfareUrgency  `json:"urgency"`
	IsAnonymous bool            `json:"isAnonymous"`
	Status      WelfareStatus   `json:"status"`
	CreatedAt   time.Time       `json:"createdAt"`
}

type EmergencyAlert struct {
	ID          string    `json:"id"`
	ChurchID    string    `json:"churchId"`
	MemberID    string    `json:"memberId"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Latitude    *float64  `json:"latitude,omitempty"`
	Longitude   *float64  `json:"longitude,omitempty"`
	IsActive    bool      `json:"isActive"`
	CreatedAt   time.Time `json:"createdAt"`
}

type VolunteerOpportunity struct {
	ID             string    `json:"id"`
	ChurchID       string    `json:"churchId"`
	Title          string    `json:"title"`
	Description    string    `json:"description"`
	Date           time.Time `json:"date"`
	SpotsAvailable float64   `json:"spotsAvailable"`
	SpotsTotal     float64   `json:"spotsTotal"`
}
